apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: smoke-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ngratzi/foundry
    targetRevision: main
    path: deploy/smoke-service
  destination:
    server: https://kubernetes.default.svc
    namespace: foundry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
