apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: smoke-workflow
  namespace: foundry
spec:
  schedule: "0 * * * *"
  timezone: "UTC"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 3
  workflowSpec:
    entrypoint: run
    templates:
      - name: run
        container:
          image: ghcr.io/ngratzi/smoke-workflow:1.0.0
          command: ["node", "job.js"]
